// login action type
export const LOGIN_START='LOGIN_START';
export const LOGIN_ERROR='LOGIN_ERROR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const CLEAR_LOGIN_STATE='CLEAR_LOGIN_STATE';

// add employee action type

export const ADD_EMPLOYEE_START='ADD_EMPLOYEE_START';
export const ADD_EMPLOYEE_ERROR='ADD_EMPLOYEE_ERROR';
export const ADD_EMPLOYEE_SUCCESS='ADD_EMPLOYEE_SUCCESS';
export const CLEAR_ADD_EMPLOYEE_STATE='CLEAR_ADD_EMPLOYEE_STATE';
// get employee
export const GET_EMPLOYEE_START='GET_EMPLOYEE_START';
export const GET_EMPLOYEE_ERROR='GET_EMPLOYEE_ERROR';
export const GET_EMPLOYEE_SUCCESS='GET_EMPLOYEE_SUCCESS';
export const CLEAR_GET_EMPLOYEE_STATE='CLEAR_GET_EMPLOYEE_STATE';
// delete employee
export const DELETE_EMPLOYEE_START='DELETE_EMPLOYEE_START';
export const DELETE_EMPLOYEE_ERROR='DELETE_EMPLOYEE_ERROR';
export const DELETE_EMPLOYEE_SUCCESS='DELETE_EMPLOYEE_SUCCESS';
export const CLEAR_DELETE_EMPLOYEE_STATE='CLEAR_DELETE_EMPLOYEE_STATE';